farm:
  box-size:
    rabbit: 60
    sheep: 24
    pig: 20
    cow: 12
    horse: 6
    small-dog: 4
    big-dog: 2
  exchange: # base value is rabbit
    sheep: 6
    pig: 12
    cow: 36
    horse: 72
    small-dog: 6
    big-dog: 36
spring:
  profiles:
    active: production
